name: Build iPerf3 APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build APK using Gradle
      run: |
        ./gradlew assembleRelease

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: iperf3-apk
        path: app/build/outputs/apk/release/*.apk
