name: Build iPerf3 for Android

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Android NDK
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r21d-linux-x86_64.zip
        unzip android-ndk-r21d-linux-x86_64.zip -d $HOME/ndk
        echo "ANDROID_NDK_HOME=$HOME/ndk/android-ndk-r21d" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential

    - name: Build iPerf3 for Android
      run: |
        mkdir build
        cd build
        cmake ../  # Chỉ định đúng đường dẫn tới thư mục chứa mã nguồn (root của repository)
        cmake --build .

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: iperf3-apk
        path: ./build/iperf3.apk
